source:
  type: postgres
  config:
    host_port: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    options:
      connect_args:
        sslmode: ${POSTGRES_SSLMODE}

    # DataHub environment
    env: ${DATAHUB_ENV}

    # Include database objects
    include_tables: true
    include_views: true

    # Lineage
    include_view_lineage: true
    include_view_column_lineage: true

    schema_pattern:
      allow:
        - public

sink:
  type: datahub-rest
  config:
    server: ${DATAHUB_GMS_URL}
    token: ${DATAHUB_GMS_TOKEN}